import { motion } from "framer-motion";

import Head from "next/head";
import mackBook from "../public/images/MacBookPro.png";
import code from "../public/images/code.png";
import meetCode from "../public/images/meetCode.png";

import Image from "next/image";
import TitleDesImg from "../components/common/TitleDesImg";
import Header from "../components/common/Header";

export default function Home() {
  const jumpUpVariants = {
    hidden: {
      x: -300,
      opacity: 0,
    },
    show: {
      x: 0,
      opacity: 1,

      transition: {
        duration: 1,
        ease: "easeInOut",
        delay: 0.3,
      },
    },
  };

  const jumpInVarient = {
    hidden: { x: 200, opacity: 0 },
    show: {
      x: 0,
      opacity: 1,

      transition: {
        duration: 0.5,
        ease: "easeInOut",
        delay: 1,
      },
    },
  };

  const zoomInVariant = {
    hidden: {
      scale: 0,
      opacity: 0,
    },
    show: {
      scale: 1,
      opacity: 1,
      transition: {
        duration: 0.5,
        ease: "easeInOut",
        delay: 1.5,
      },
    },
  };

  return (
    <>
      <Head>
        <title>Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container m-auto">
        <div className="font-primary py-20 sm:text-left text-center">
          <motion.h2
            className="text-5xl"
            variants={jumpUpVariants}
            initial="hidden"
            whileInView={"show"}
            viewport={{ once: true }}
          >
            MeetCode
          </motion.h2>
          <motion.p
            className="text-2xl flex sm:flex-row flex-col items-center gap-3 pt-3 text-[#6C6C6C] font-[300]"
            variants={jumpInVarient}
            initial="hidden"
            whileInView={"show"}
            viewport={{ once: true }}
          >
            <span>Co-Creator</span> <span className="dot"></span>{" "}
            <span>UI/UX Designer</span> <span className="dot"></span>{" "}
            <span>2022</span>
          </motion.p>
        </div>
        <motion.div
          className="w-full h-auto"
          variants={zoomInVariant}
          initial="hidden"
          whileInView={"show"}
          viewport={{ once: true }}
        >
          <Image src={mackBook} alt="MacBook Pro" className="w-full h-auto" />
        </motion.div>
        <div className="bg-[#FFF6EE] p-12 flex items-center justify-between sm:flex-row flex-col gap-6 rounded-xl max-w-[80%] mx-auto">
          <div className="flex items-center flex-col w-[49%]">
            <h2 className="text-5xl font-secondary font-medium text-[#696969]">
              {"Position".split("").map((letter, index) => (
                <motion.span
                  key={index}
                  initial={{
                    opacity: 0,
                    x: -100,
                  }}
                  whileInView={{
                    opacity: 1,
                    x: 0,
                  }}
                  viewport={{
                    once: false,
                  }}
                  transition={{
                    duration: 0.08 * index,
                    ease: "easeInOut",
                    delay: 0.08 * index,
                  }}
                >
                  {letter === " " ? "&nbsp;" : letter}
                </motion.span>
              ))}
            </h2>
            <p className="font-primary text-2xl pt-1 text-[#7A7A7A] text-center">
              UI/UX Designer
            </p>
          </div>
          <div className="bg-[#787878] sm:h-[7rem] h-0.5 sm:w-0.5 w-full"></div>
          <div className="flex flex-col items-center w-[49%]">
            <h2 className="text-5xl font-secondary font-medium text-[#696969]">
              {"Tools".split("").map((letter, index) => (
                <motion.span
                  key={index}
                  initial={{
                    opacity: 0,
                    x: -100,
                  }}
                  whileInView={{
                    opacity: 1,
                    x: 0,
                  }}
                  viewport={{
                    once: false,
                  }}
                  transition={{
                    duration: 0.08 * index,
                    ease: "easeInOut",
                    delay: 0.08 * index,
                  }}
                >
                  {letter === " " ? "&nbsp;" : letter}
                </motion.span>
              ))}
            </h2>
            <p className="font-primary text-2xl pt-1 text-[#7A7A7A]">Figma</p>
          </div>
        </div>
        <div className="pt-16">
          <TitleDesImg
            title={"The Problem"}
            des="While in my second year of college, my roomate and I decided to work on a website to not only challenge ourselves, but to create a tool that can help our community. We discovered that developers need a platform in order to colaborate with other developers in order to solve frequently asked question in coding related interviews. "
            img={code}
          />
        </div>
        <div className="pt-16">
          <TitleDesImg
            title={"Solution"}
            des="We created an online platform called MeetCode, where you are randomly placed in a room with another developer while being presented a coding challenge in which you must work together in order to solve it. We also allowed for users to create their own profile where they can add people that they worked together with in order to keep a long lasting connection."
            img={meetCode}
          />
        </div>
        <div className="py-16">
          <TitleDesImg
            title={"What I learned"}
            des="I learned how to use Figma to its fullest potential. This was once again a great way to practice my collaboration skills,. but also test my knowledge with Figma, as well as using plugins from various sections of the Figma community. I learned the power of creating a strong structure and frame for a website, and also, the important of constnatly being organized with icons, hex codes, and images. "
          />
        </div>
      </main>
      <footer className="bg-[#FFDBA6] flex flex-col gap-6 items-center font-primary p-8">
        <h2 className="text-4xl font-medium text-[#464646]">Contact</h2>
        <div className="w-2 h-2 transform rotate-45 bg-[#464646]"></div>
        <div className="text-center">
          <p className="text-2xl text-[#464646]">lecristo@ucsc.edu</p>
          <p className="text-2xl text-[#464646]">(323) 817-9583</p>
        </div>
        <div className="w-2 h-2 transform rotate-45 bg-[#464646]"></div>
        <div className="flex flex-col items-center">
          <a className="text-3xl text-[#464646] underline font-medium">
            LinkedIn
          </a>
          <a className="text-3xl text-[#464646] underline font-medium">
            Instagram
          </a>
        </div>
      </footer>
    </>
  );
}
